const ACTIONS = {
  CREATE_TRANSACTION_REQUEST: 'CREATE_TRANSACTION_REQUEST',
  CREATE_TRANSACTION_SUCCESS: 'CREATE_TRANSACTION_SUCCESS',
  CREATE_TRANSACTION_ERROR: 'CREATE_TRANSACTION_ERROR',

  GET_TRANSACTIONS_REQUEST: 'GET_TRANSACTIONS_REQUEST',
  GET_TRANSACTIONS_SUCCESS: 'GET_TRANSACTIONS_SUCCESS',
  GET_TRANSACTIONS_ERROR: 'GET_TRANSACTIONS_ERROR',
};

export default ACTIONS;
